version : '3.8'

services:
    mysql-db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: HOy%r<5obb_k
            MYSQL_DATABASE: wiki_database
            MYSQL_USER: sathya
            MYSQL_PASSWORD: Sathyajith@123
    
#    python-app:
#        depends_on:
#            - mysql-db
#        build:
#            context: ./app

    crawler:
        depends_on:
            - mysql-db
        image: sathyajith91/crawler:1.4
        #build:
        #    context: ./app
    
    flask-app:
        depends_on:
            - mysql-db
            - crawler
        image: sathyajith91/flask-app:1.4
        #build:
        #    context: ./flaskapp
        ports:
            - 5000:5000

volumes:
    db_data: {}

#docker exec -it inter_tests_mysql-db_1 bash
#docker volume rm $(docker volume ls -q)