version : '3.8'

services:
    mysql-db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USR}
            MYSQL_PASSWORD: ${MYSQL_PASS}

    crawler:
        depends_on:
            - mysql-db
        image: sathyajith91/crawler:1.5
        #build:
        #    context: ./app
        environment: 
            MYSQL_USER: ${MYSQL_USR}
            MYSQL_PASSWORD: ${MYSQL_PASS}
    
    flask-app:
        depends_on:
            - mysql-db
            - crawler
        image: sathyajith91/flask-app:1.5
        #build:
        #    context: ./flaskapp
        ports:
            - 5000:5000
        environment: 
            MYSQL_USER: ${MYSQL_USR}
            MYSQL_PASSWORD: ${MYSQL_PASS}

volumes:
    db_data: {}
